name: Build and Push Docker Image

on:
  push:
    branches:
      - main   # Change en "master" si ta branche principale est master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer ton code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Installer Docker Buildx (outil pour build moderne)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Se connecter à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Builder et push l’image
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: palaye769/projetpython:latest
